export enum EntityType {
    MENU = 'MENU',
    MENU_CATEGORY = 'MENU_CATEGORY',
    MENU_ITEM = 'MENU_ITEM',
    MENU_OPTION_ITEM = 'MENU_OPTION_ITEM',
    MENU_OPTIONS = 'MENU_OPTIONS',
    CUSTOMER = 'CUSTOMER',
    ORDER = 'ORDER'
  }